itemsData = [
    {imageName:"blue painting",itemType:"painting", hue:186},
    {imageName:"blue pillow three",itemType:"pillow", hue:216},
    {imageName:"blue pillow two",itemType:"pillow", hue:208},
    {imageName:"blue pillow",itemType:"pillow", hue:241},
    {imageName:"blue pot",itemType:"pot", hue:199},
    {imageName:"brown clock",itemType:"clock", hue:25},
    {imageName:"brown cup mat",itemType:"cupMat", hue:33},
    {imageName:"brown frame",itemType:"frame", hue:31},
    {imageName:"cream frame",itemType:"frame", hue:40},
    {imageName:"cyan cup",itemType:"cup", hue:185},
    {imageName:"cyan painting",itemType:"painting", hue:175},
    {imageName:"cyan pot",itemType:"pot", hue:174},
    {imageName:"gold lamp two",itemType:"lamp", hue:21},
    {imageName:"gold lamp",itemType:"lamp", hue:28},
    {imageName:"green cup",itemType:"cup", hue:154},
    {imageName:"green frame",itemType:"frame", hue:130},
    {imageName:"green painting two",itemType:"painting", hue:162},
    {imageName:"green painting",itemType:"painting", hue:135},
    {imageName:"green pillow two",itemType:"pillow", hue:48},
    {imageName:"green pillow",itemType:"pillow", hue:130},
    {imageName:"green pot",itemType:"pot", hue:158},
    {imageName:"green wardrob",itemType:"wardrob", hue:167},
    {imageName:"grey lamp",itemType:"lamp", hue:191},
    {imageName:"grey pot",itemType:"pot", hue:220},
    {imageName:"mustard sofa",itemType:"sofa", hue:35},
    {imageName:"orange chair",itemType:"chair", hue:30},
    {imageName:"orange cup two",itemType:"cup", hue:9},
    {imageName:"orange cup",itemType:"cup", hue:19},
    {imageName:"orange pillow two",itemType:"pillow", hue:21},
    {imageName:"orange pillow",itemType:"pillow", hue:13},
    {imageName:"orange pot",itemType:"pot", hue:22},
    {imageName:"orange sofa two",itemType:"sofa", hue:27},
    {imageName:"orange sofa",itemType:"sofa", hue:15},
    {imageName:"orange halloween",itemType:"showpeice", hue:17},
    {imageName:"pink balls",itemType:"balls", hue:328},
    {imageName:"pink chair three",itemType:"chair", hue:340},
    {imageName:"pink chair two",itemType:"chair", hue:330},
    {imageName:"pink chair",itemType:"chair", hue:352},
    {imageName:"pink disc",itemType:"disc", hue:359},
    {imageName:"pink lamp",itemType:"lamp", hue:16},
    {imageName:"pink painting",itemType:"painting", hue:11},
    {imageName:"pink photo frame",itemType:"frame", hue:348},
    {imageName:"pink pillow",itemType:"pillow", hue:8},
    {imageName:"pink sofa",itemType:"sofa", hue:337},
    {imageName:"purple chair",itemType:"chair", hue:289},
    {imageName:"purple table",itemType:"table", hue:283},
    {imageName:"red balls",itemType:"balls", hue:13},
    {imageName:"red chair two",itemType:"chair", hue:355},
    {imageName:"red chair",itemType:"chair", hue:2},
    {imageName:"red cup",itemType:"cup", hue:359},
    {imageName:"red pillow",itemType:"pillow", hue:355},
    {imageName:"red pot",itemType:"pot", hue:3},
    {imageName:"white painting",itemType:"painting", hue:114},
    {imageName:"yellow chair two",itemType:"chair", hue:50},
    {imageName:"yellow chair",itemType:"chair", hue:45},
    {imageName:"yellow pillow",itemType:"pillow", hue:52}
];